# Generated by Django 2.2.3 on 2019-10-19 16:00

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20191014_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='music/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 15, 59, 55, 2951, tzinfo=utc)),
        ),
    ]
