# Generated by Django 2.2.3 on 2019-10-19 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20191019_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 16, 1, 46, 983252, tzinfo=utc)),
        ),
    ]
