# Generated by Django 2.2.3 on 2019-10-19 20:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20191019_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='file',
        ),
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='music/%Y/%m/%d'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 19, 20, 0, 13, 24774, tzinfo=utc)),
        ),
    ]
